apiVersion: v2
name: twitter-app
version: 0.1.11
dependencies:
  - name: twitter-graphql
    repository: https://stakkato95.github.io/twitter-graphql
    version: 0.1.2
  - name: twitter-users
    repository: https://stakkato95.github.io/twitter-users
    version: 0.1.0
  - name: twitter-tweets
    repository: https://stakkato95.github.io/twitter-tweets
    version: 0.1.0
  - name: twitter-analytics
    repository: https://stakkato95.github.io/twitter-analytics
    version: 0.1.0
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 9.1.7
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.6.5
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 17.2.6
